name: Simple Go Build

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5.0.0
      with:
        python-version: '3.10'
    - run: python -m main
